// Anonymous API responses recorded from calculator 2b23925473024b9883cd85f7c62509cd626172ab.
// Keep fixed: CI must not require historical Git objects during test discovery.
export const baseline = {
  "strong": {
    "forecasts": [
      {
        "projected_sponsor": 240000,
        "projected_sponsor_base": 240000,
        "projected_sponsor_variable": 0,
        "projected_division_adjustment": 0,
        "projected_prize": 200000,
        "prize_low": 175,
        "prize_high": 200000,
        "projected_salary": -35000,
        "projected_loan_interest": 0,
        "projected_upkeep": -220000,
        "projected_upkeep_at_season_start": -220000,
        "projected_facility_upkeep": 0,
        "projected_staff_salary": 0,
        "projected_staff_facilities": 0,
        "projected_academy_drift": 0,
        "projected_net": 185000,
        "confidence_low": -14825,
        "confidence_high": 185000,
        "risk_tier": "green",
        "warnings": [],
        "inputs": {
          "sponsor_base": 240000,
          "sponsor_variable": 0,
          "sponsor_mode": "fallback",
          "sponsor_gross": 240000,
          "sponsor_breakdown": {
            "mode": "fallback",
            "season_number": 5,
            "base": 240000,
            "variable": 0,
            "gross_sponsor": 240000,
            "capped": false,
            "explanation": "Mangler forrige sæsons standings: bruger legacy sponsor."
          },
          "board_modifier": 1,
          "pullout_factor": 1,
          "prize_rolling_avg": 200000,
          "realized_season_prize": 0,
          "prize_basis": "rolling_avg",
          "prize_interval_method": "division_quartile_band",
          "prize_interval_sample_size": 4,
          "team_balance": 500000,
          "total_salary": 35000,
          "salary_basis": "production_s3",
          "total_debt": 0,
          "debt_ceiling": 900000,
          "debt_ratio": 0,
          "rider_count": 1,
          "active_loan_count": 0,
          "current_season_number": 4,
          "target_season_number": 5,
          "upkeep_deferred": false,
          "division_upkeep": 220000,
          "upkeep_model": "season_start",
          "upkeep_per_race_day": 1571,
          "upkeep_race_days": null,
          "facilities_enabled": true,
          "facility_track_count": 0,
          "facility_upkeep_total": 0,
          "active_staff_count": 0,
          "staff_salary_total": 0,
          "academy_rider_count": 0,
          "academy_drift_per_slot": 5000
        },
        "season_number": 5,
        "is_estimate": false,
        "estimate_basis": "actual_state",
        "starting_balance": 500000,
        "ending_balance": 685000
      }
    ],
    "summary": {
      "seasons_ahead": 1,
      "starting_balance": 500000,
      "ending_balance": 685000,
      "total_net": 185000,
      "worst_risk_tier": "green",
      "from_season": 5,
      "to_season": 5
    },
    "warnings_all": []
  },
  "low-division": {
    "forecasts": [
      {
        "projected_sponsor": 240000,
        "projected_sponsor_base": 240000,
        "projected_sponsor_variable": 0,
        "projected_division_adjustment": 0,
        "projected_prize": 200,
        "prize_low": 175,
        "prize_high": 325,
        "projected_salary": -35000,
        "projected_loan_interest": 0,
        "projected_upkeep": 0,
        "projected_upkeep_at_season_start": 0,
        "projected_facility_upkeep": 0,
        "projected_staff_salary": 0,
        "projected_staff_facilities": 0,
        "projected_academy_drift": 0,
        "projected_net": 205200,
        "confidence_low": 205175,
        "confidence_high": 205325,
        "risk_tier": "green",
        "warnings": [],
        "inputs": {
          "sponsor_base": 240000,
          "sponsor_variable": 0,
          "sponsor_mode": "fallback",
          "sponsor_gross": 240000,
          "sponsor_breakdown": {
            "mode": "fallback",
            "season_number": 5,
            "base": 240000,
            "variable": 0,
            "gross_sponsor": 240000,
            "capped": false,
            "explanation": "Mangler forrige sæsons standings: bruger legacy sponsor."
          },
          "board_modifier": 1,
          "pullout_factor": 1,
          "prize_rolling_avg": 200,
          "realized_season_prize": 0,
          "prize_basis": "rolling_avg",
          "prize_interval_method": "division_quartile_band",
          "prize_interval_sample_size": 4,
          "team_balance": 500000,
          "total_salary": 35000,
          "salary_basis": "production_s3",
          "total_debt": 0,
          "debt_ceiling": 900000,
          "debt_ratio": 0,
          "rider_count": 1,
          "active_loan_count": 0,
          "current_season_number": 4,
          "target_season_number": 5,
          "upkeep_deferred": false,
          "division_upkeep": 0,
          "upkeep_model": "season_start",
          "upkeep_per_race_day": 0,
          "upkeep_race_days": null,
          "facilities_enabled": true,
          "facility_track_count": 0,
          "facility_upkeep_total": 0,
          "active_staff_count": 0,
          "staff_salary_total": 0,
          "academy_rider_count": 0,
          "academy_drift_per_slot": 5000
        },
        "season_number": 5,
        "is_estimate": false,
        "estimate_basis": "actual_state",
        "starting_balance": 500000,
        "ending_balance": 705200
      }
    ],
    "summary": {
      "seasons_ahead": 1,
      "starting_balance": 500000,
      "ending_balance": 705200,
      "total_net": 205200,
      "worst_risk_tier": "green",
      "from_season": 5,
      "to_season": 5
    },
    "warnings_all": []
  },
  "realized-floor": {
    "forecasts": [
      {
        "projected_sponsor": 240000,
        "projected_sponsor_base": 240000,
        "projected_sponsor_variable": 0,
        "projected_division_adjustment": 0,
        "projected_prize": 1000,
        "prize_low": 175,
        "prize_high": 1000,
        "projected_salary": -35000,
        "projected_loan_interest": 0,
        "projected_upkeep": 0,
        "projected_upkeep_at_season_start": 0,
        "projected_facility_upkeep": 0,
        "projected_staff_salary": 0,
        "projected_staff_facilities": 0,
        "projected_academy_drift": 0,
        "projected_net": 206000,
        "confidence_low": 205175,
        "confidence_high": 206000,
        "risk_tier": "green",
        "warnings": [],
        "inputs": {
          "sponsor_base": 240000,
          "sponsor_variable": 0,
          "sponsor_mode": "fallback",
          "sponsor_gross": 240000,
          "sponsor_breakdown": {
            "mode": "fallback",
            "season_number": 5,
            "base": 240000,
            "variable": 0,
            "gross_sponsor": 240000,
            "capped": false,
            "explanation": "Mangler forrige sæsons standings: bruger legacy sponsor."
          },
          "board_modifier": 1,
          "pullout_factor": 1,
          "prize_rolling_avg": 200,
          "realized_season_prize": 1000,
          "prize_basis": "realized_season_floor",
          "prize_interval_method": "division_quartile_band",
          "prize_interval_sample_size": 4,
          "team_balance": 500000,
          "total_salary": 35000,
          "salary_basis": "production_s3",
          "total_debt": 0,
          "debt_ceiling": 900000,
          "debt_ratio": 0,
          "rider_count": 1,
          "active_loan_count": 0,
          "current_season_number": 4,
          "target_season_number": 5,
          "upkeep_deferred": false,
          "division_upkeep": 0,
          "upkeep_model": "season_start",
          "upkeep_per_race_day": 0,
          "upkeep_race_days": null,
          "facilities_enabled": true,
          "facility_track_count": 0,
          "facility_upkeep_total": 0,
          "active_staff_count": 0,
          "staff_salary_total": 0,
          "academy_rider_count": 0,
          "academy_drift_per_slot": 5000
        },
        "season_number": 5,
        "is_estimate": false,
        "estimate_basis": "actual_state",
        "starting_balance": 500000,
        "ending_balance": 706000
      }
    ],
    "summary": {
      "seasons_ahead": 1,
      "starting_balance": 500000,
      "ending_balance": 706000,
      "total_net": 206000,
      "worst_risk_tier": "green",
      "from_season": 5,
      "to_season": 5
    },
    "warnings_all": []
  }
} as const;
