-- Refs #1994: remove the player-facing "rider loan" (udlån/leje) feature.
-- APPLY-KORREKTION 12/7: PR-kommentaren påstod "ZERO rows ever" — ved apply
-- indeholdt tabellen 2 rækker, BEGGE status='rejected' (afviste tilbud 3/7 +
-- 8/7, ingen aktive aftaler eller økonomiske forpligtelser). Droppet mister
-- derfor kun historik om to afviste tilbud. Applied mod prod 12/7 EFTER
-- Railway-deploy af den kode-fjernede backend (rækkefølge: kode først, DDL
-- bagefter). All application code that read/wrote this table was removed in
-- the same PR as this migration.
--
-- Do NOT confuse this with the unrelated "team debt loan" feature (tables
-- `loans` / `loan_config`, short/long/emergency loans against a team's own
-- balance) — that feature is untouched and stays live (35 rows at apply).
--
-- CASCADE drops the table's own indexes, constraints, and RLS policies
-- along with it — none of those objects are referenced by any other table.
DROP TABLE IF EXISTS loan_agreements CASCADE;
